FROM continuumio/anaconda3:latest
RUN apt update -y && apt-get install libgl1 wget build-essential libglu1 git vim -y

RUN adduser --disabled-password --gecos "Default user" --uid 1000 cc

RUN mkdir /opt/conda/pkgs && \
    chgrp cc /opt/conda/pkgs && \
    chmod g+w -R /opt/conda /opt/conda/pkgs && \
    touch /opt/conda/pkgs/urls.txt && \
    chown cc  -R /opt/conda /opt/conda/pkgs/urls.txt

USER cc

RUN conda install -c anaconda jupyter nb_conda_kernels -y

RUN git clone https://github.com/ValHayot/parsl-docking-tutorial.git /home/cc/parsldock

WORKDIR /home/cc/parsldock
RUN conda env create --file docker/environment.yml
RUN conda update -c defaults jupyter -y


ENV MGLTOOLS_HOME=/opt/conda/envs/parsldockenv

SHELL ["conda", "run", "--no-capture-output", "-n", "parsldockenv", "/bin/bash", "-c"]


RUN pip install -e . && pip install hatchling pytest pandas==2.2.0  \
    jupyter==1.1.1 seaborn==0.13.2 matplotlib==3.8.2 globus-compute-endpoint==3.5.0

RUN mkdir -p /home/cc/pd_cache && cd /home/cc/pd_cache && pip download /home/cc/parsldock \
    && pip download hatchling pytest pandas==2.2.0 jupyter==1.1.1 seaborn==0.13.2 matplotlib==3.8.2 \
        globus-compute-endpoint==3.5.0

RUN globus-compute-endpoint configure --multi-user mep-ci

COPY ../a3/chameleon_user_config_template.yaml.j2 /home/cc/.globus_compute/mep-ci/user_config_template.yaml.j2
